export const Images = {
  REMOTEHIRELOGO: "/Images/ERH_Vector_Logo_New.png",
  REMOTEHIRELOGODark: "/Images/ERH_Light_Logo.svg",
  RAHULSAHAI: "/Images/Men.png",
  BENIFITS: "/Images/benefits.png",
  STAR: "/Images/star.png",
  STOPWATCH: "/Images/Stopwatch Play.png",
  ARROWLONGTOSCO: "/Images/Arrow Right-tosco.png",
  ARROWLONGBLACK: "/Images/Arrow Right-black.png",
  PHONE: "/Images/Phone.png",
  MSG: "/Images/Letter.png",
  PHONE_WHITE: "/Images/Phone_white.png",
  MSG_WHITE: "/Images/Letter_white.png",
  CHAIR: "/Images/chair.png",
  FAVOURITE: "/Images/favourite.png",
  LAPTOP: "/Images/laptop.png",
  MED_CAR: "/Images/medcar.png",
  MONEY_BAG: "/Images/money-bag.png",
  TREE: "/Images/tree.png",
  WORLD:"/Images/world.png"
};
export const Strings = {
  BACK: "Back",
  DEVELOPERS: "Developers",
  DEVELOPER_DETAILS: "Developer details",
  REPLACMENT_REQUSET: "Replacement requested",
  GIVE_BOUNS: "Give bonus",
  GIVE_RAISE: "Give Raise",
  DASHBOARD: "Dashboard",
  HIRE_NEW_TALENT: "Hire New Talent",
  YOUR_ACCOUNT_MANAGER: "YOUR ACCOUNT MANAGER",
  HAND_PICKED_RECOMMENDATIONS: "Hand picked recommendations",
  HIRED_ENGINEERS: "HIRED ENGINEERS",
  DEVELOPER_NAME: "Mihir Mistry",
  EMAIL: "eremotehire@gmail.com",
  CONTACT_NUMBER: "+91 99985 78704",
  DEVELOPERR:"Developer",
  ROLE:"Role ",
  AMOUNT:" Amount",
  SENT_ON:"Sent On",
  EFFECTIVE_ON:'Effective On',
  HOURS_WORKED:"HOURS WORKED",
  WORK_TYPE:"WORK TYPE",
  BOUNS_GIVEN:'BOUNS GIVEN',
  MONTHLY_SALARY:"MONTHLY SALARY",
  PERFORMANCE:"PERFORMANCE",
  WEEKLY_SUMMARIES:"WEEKLY SUMMARIES",
  RAISE:" Raise",
  BOUNS_HISTORY:"Bouns history",
  RAISE_HISTORY:"Raise history",
  BENEFITS:" Benefits",
  SETTINGS:"Settings",
  VETTING:"Vetting results"
};
