export const Images = {
  REMOTEHIRELOGO: "/Images/ERH_Vector_Logo_New.png",
  REMOTEHIRELOGODark: "/Images/ERH_Light_Logo.svg",
  RAHULSAHAI: "/Images/Men.png",
  BENIFITS: "/Images/benefits.png",
  STAR: "/Images/star.png",
  STOPWATCH: "/Images/Stopwatch Play.png",
  ARROWLONGTOSCO: "/Images/Arrow Right-tosco.png",
  ARROWLONGBLACK: "/Images/Arrow Right-black.png",
  PHONE: "/Images/Phone.png",
  MSG: "/Images/Letter.png",
  PHONE_WHITE: "/Images/Phone_white.png",
  MSG_WHITE: "/Images/Letter_white.png",
};
export const Strings = {
  BACK: "Back",
  DEVELOPERS: "Developers",
  DEVELOPER_DETAILS: "Developer details",
  REPLACMENT_REQUSET: "Replacement requested",
  GIVE_BOUNS: "Give bonus",
  GIVE_RAISE: "Give Raise",
  DASHBOARD: "Dashboard",
  HIRE_NEW_TALENT: "Hire New Talent",
  YOUR_ACCOUNT_MANAGER: "YOUR ACCOUNT MANAGER",
  HAND_PICKED_RECOMMENDATIONS: "Hand picked recommendations",
  HIRED_ENGINEERS: "HIRED ENGINEERS",
  DEVELOPER_NAME: "Mihir Mistry",
  EMAIL: "eremotehire@gmail.com",
  CONTACT_NUMBER: "+91 99985 78704"
};
